### ISSUE TITLE
Extension search and scrapeApp are not working 

### ISSUE THREAD

**Issue by NewAlexandria** [AdamSlack/chrome-web-store-scraper#8]
Probably the element changed.  I haven't had time to look, but if you do then thank you for the fix!

**Comment by AdamSlack** [comment]
Literally a couple of days after i finished the first version the chrome extension store totally changed, im gonna get round to fixing it eventually, thanks for letting me know :)

**Comment by AdamSlack** [comment]
I've fixed some of the issues with the scraping of an individual app in #9. Though there is some more fixes needed for Reviews, and getting the Rating.

**Comment by AdamSlack** [comment]
This has been resolved for now, need to publish the changes to npm though.
